# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('call_sent', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('call_url', models.URLField(blank=True, null=True)),
                ('proposal_type', models.CharField(choices=[('SCI', 'Science'), ('DDT', "Director's Discretionary Time"), ('KEY', 'Key Project'), ('NOAC', 'NOAC proposal')], max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='sciapp/call/')),
                ('eligibility', models.TextField(blank=True, default='')),
                ('eligibility_short', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True, default='')),
                ('pi', models.EmailField(blank=True, default='', max_length=254)),
                ('coi', models.TextField(blank=True, default='')),
                ('budget_details', models.TextField(blank=True, default='')),
                ('moon', models.CharField(blank=True, choices=[('EITHER', 'Either'), ('BRIGHT', 'Bright'), ('DARK', 'Dark')], default='EITHER', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PORTED', 'Ported')], default='DRAFT', max_length=50)),
                ('science_case', models.FileField(blank=True, null=True, upload_to='sciapp/sci_case/')),
                ('experimental_design', models.TextField(blank=True, default='')),
                ('experimental_design_file', models.FileField(blank=True, null=True, upload_to='sciapp/tech/')),
                ('related_programs', models.TextField(blank=True, default='')),
                ('past_use', models.TextField(blank=True, default='')),
                ('publications', models.TextField(blank=True, default='')),
                ('final', models.FileField(blank=True, null=True, upload_to='sciapp/final/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sciapp/attachment/')),
                ('science_justification', models.TextField(blank=True, default='')),
                ('ddt_justification', models.TextField(blank=True, default='')),
                ('management', models.TextField(blank=True, default='')),
                ('relevance', models.TextField(blank=True, default='')),
                ('contribution', models.TextField(blank=True, default='')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciapplications.Call')),
                ('instruments', models.ManyToManyField(blank=True, to='sciapplications.Instrument')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope_class', models.CharField(choices=[('2m0', '2m0'), ('1m0', '1m0'), ('0m8', '0m8'), ('0m4', '0m4')], max_length=20)),
                ('std_time', models.PositiveIntegerField(default=0)),
                ('too_time', models.PositiveIntegerField(default=0)),
                ('science_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciapplications.ScienceApplication')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='instruments',
            field=models.ManyToManyField(to='sciapplications.Instrument'),
        ),
        migrations.AddField(
            model_name='call',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Semester'),
        ),
    ]
