# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scienceapplication',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='final',
        ),
        migrations.AlterField(
            model_name='scienceapplication',
            name='coi',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
