# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0002_auto_20170123_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerequest',
            name='std_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timerequest',
            name='too_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
