# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0003_auto_20170320_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceapplication',
            name='moon',
            field=models.CharField(blank=True, choices=[('EITHER', 'Any'), ('BRIGHT', 'Bright'), ('DARK', 'Dark')], default='EITHER', max_length=50),
        ),
    ]
