# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sciapplications', '0005_auto_20171011_1813'), ('sciapplications', '0006_remove_scienceapplication_instruments')]

    dependencies = [
        ('sciapplications', '0004_auto_20170524_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerequest',
            name='telescope_class',
        ),
        migrations.AddField(
            model_name='instrument',
            name='display',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='telescope_class',
            field=models.CharField(choices=[('2m0', '2m0'), ('1m0', '1m0'), ('0m8', '0m8'), ('0m4', '0m4')], default='1M0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timerequest',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sciapplications.Instrument'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='instruments',
        ),
    ]
