# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0005_auto_20171011_1813_squashed_0006_remove_scienceapplication_instruments'),
        ('sciapplications', '0005_auto_20171128_0046'),
    ]

    operations = [
    ]
