# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0006_merge_20171130_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('science_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciapplications.ScienceApplication')),
            ],
        ),
    ]
