# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0007_coinvestigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Add notes here. Not visible to users.'),
        ),
    ]
