# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0008_scienceapplication_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceapplication',
            name='coi',
        ),
    ]
