# Generated by Django 2.0.2 on 2018-02-07 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0010_auto_20180102_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scienceapplication',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scienceapplication',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
