# Generated by Django 2.0.2 on 2018-02-20 15:27

from django.db import migrations, models
import valhalla.sciapplications.models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0012_auto_20180213_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=valhalla.sciapplications.models.pdf_upload_path),
        ),
    ]
