# Generated by Django 2.0.2 on 2018-02-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0014_timerequest_crt_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceapplication',
            name='budget_details',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='ddt_justification',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='experimental_design',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='experimental_design_file',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='management',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='past_use',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='related_programs',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='science_case',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='science_case_file',
        ),
        migrations.RemoveField(
            model_name='scienceapplication',
            name='science_justification',
        ),
    ]
