# Generated by Django 2.0.3 on 2018-03-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0017_timerequest_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timerequest',
            options={'ordering': ('semester',)},
        ),
    ]
