# Generated by Django 2.0.3 on 2018-03-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0018_auto_20180319_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinvestigator',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
