# Generated by Django 2.0.3 on 2018-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0019_auto_20180321_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceapplication',
            name='submitter_rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
