# Generated by Django 2.0.4 on 2018-04-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0020_auto_20180327_2033'),
        ('sciapplications', '0020_scienceapplication_submitter_rank'),
    ]

    operations = [
    ]
