# Generated by Django 2.0.4 on 2018-04-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciapplications', '0021_merge_20180405_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scienceapplication',
            name='submitter_rank',
        ),
    ]
