# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0002_auto_20161018_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
    ]
