# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0003_auto_20161019_2107'),
        ('userrequests', '0004_draftuserrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftuserrequest',
            options={'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='draftuserrequest',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='draftuserrequest',
            unique_together=set([('author', 'proposal', 'title')]),
        ),
    ]
