# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0005_auto_20170217_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='type',
            field=models.CharField(choices=[('EXPOSE', 'EXPOSE'), ('SKY_FLAT', 'SKY_FLAT'), ('STANDARD', 'STANDARD'), ('ARC', 'ARC'), ('LAMP_FLAT', 'LAMP_FLAT'), ('SPECTRUM', 'SPECTRUM'), ('AUTO_FOCUS', 'AUTO_FOCUS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='ipp_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='observation_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('TARGET_OF_OPPORTUNITY', 'TARGET_OF_OPPORTUNITY')], max_length=40),
        ),
    ]
