# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0006_auto_20170224_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='defocus',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
