# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0007_auto_20170308_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='max_airmass',
            field=models.FloatField(default=1.6, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(25.0)]),
        ),
    ]
