# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0008_auto_20170315_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
