# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0009_auto_20170324_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='epoch',
            field=models.FloatField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='parallax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='proper_motion_dec',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='proper_motion_ra',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
