# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0010_auto_20170418_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='acquire_mode',
        ),
    ]
