# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0011_remove_target_acquire_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='acquire_strategy',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
        migrations.AddField(
            model_name='molecule',
            name='ag_strategy',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
        migrations.AddField(
            model_name='molecule',
            name='expmeter_mode',
            field=models.CharField(blank=True, default='OFF', max_length=12),
        ),
        migrations.AddField(
            model_name='molecule',
            name='expmeter_snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='radvel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='vmag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='type',
            field=models.CharField(choices=[('EXPOSE', 'EXPOSE'), ('SKY_FLAT', 'SKY_FLAT'), ('STANDARD', 'STANDARD'), ('ARC', 'ARC'), ('LAMP_FLAT', 'LAMP_FLAT'), ('SPECTRUM', 'SPECTRUM'), ('AUTO_FOCUS', 'AUTO_FOCUS'), ('TRIPLE', 'TRIPLE'), ('NRES_TEST', 'NRES_TEST'), ('NRES_SPECTRUM', 'NRES_SPECTRUM'), ('NRES_EXPOSE', 'NRES_EXPOSE'), ('ENGINEERING', 'ENGINEERING')], max_length=50),
        ),
    ]
