# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0012_auto_20170515_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constraints',
            options={'ordering': ('id',), 'verbose_name_plural': 'Constraints'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='molecule',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ('id',)},
        ),
    ]
