# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0013_auto_20170524_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completion_threshold',
            field=models.FloatField(default=90.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
