# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0014_request_completion_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
