# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0015_auto_20170918_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accounted',
            field=models.BooleanField(default=False),
        ),
    ]
