# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0015_auto_20170918_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='completion_threshold',
            field=models.FloatField(default=90.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
