# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0017_auto_20171010_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='completion_threshold',
            new_name='acceptability_threshold',
        ),
    ]
