# Generated by Django 2.0.1 on 2018-02-12 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0018_auto_20171011_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='exposure_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
