# Generated by Django 2.0.3 on 2018-08-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0019_auto_20180212_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='type',
            field=models.CharField(choices=[('EXPOSE', 'EXPOSE'), ('SKY_FLAT', 'SKY_FLAT'), ('STANDARD', 'STANDARD'), ('ARC', 'ARC'), ('LAMP_FLAT', 'LAMP_FLAT'), ('SPECTRUM', 'SPECTRUM'), ('AUTO_FOCUS', 'AUTO_FOCUS'), ('TRIPLE', 'TRIPLE'), ('NRES_TEST', 'NRES_TEST'), ('NRES_SPECTRUM', 'NRES_SPECTRUM'), ('NRES_EXPOSE', 'NRES_EXPOSE'), ('ENGINEERING', 'ENGINEERING'), ('SCRIPT', 'SCRIPT')], max_length=50),
        ),
    ]
