language: python
python:
- '3.5'
- '3.6'
env:
- NODE_VERSION='7'
before_install:
- nvm install $NODE_VERSION
addons:
  apt:
    packages:
    - gfortran
install:
- pip install -U setuptools coverage coveralls
- pip install -r requirements.txt
- npm install
- npm run build
script: coverage run manage.py test
after_success: coveralls
notifications:
  slack:
    secure: b1mrHVdf9SVXcYqp8IDbGzMPsHkCM8rjkA4dklPvkIbsfJNpAwLb1fq45siYy4lVe0I/RJSSa4ysBWEC7SKTqYbn8Jssaj0LfnlJ6xsjdak+fbe3dEfMxgJaZYN7OHgZqYO2UzaENl5rBn2iPOgkpPONVTYorN4l/KVCK638AZVGGNWOHAH8U4OeV1y22TZcKUUHcWhvFZcmGEkmkXkzw2uCNuIRWEIgNFNe8UXkWvvj7zBYReNBbwUzPC9sAycFRKQXcIIeDe2l5oECKydoPHS05eip6UNVFw+IESYse2bxenZ9zn3bfbhPEoVfCkZYaCiHBmNG/vvyJkaGl3pny4wuEGWPRE5LBAFy41dGVUZHq6G3CFOsbDoypI4bNHS+P+F7pbhYWiw+qu3fLhLye5U8oqBjF/Yijaw8iI3t7dH2zyiDNGeRKHw4b9rSPVNrxvDb44bsG8i92CqIPDz7Aa8A+JNtbowQFkH0/CM6BH01VSI9hTpg7esVom2/qqwqaViajrxJlckoFpE2gFCSvMN5KxRLnxW3RZDaaNljlWVOnD/3Qg02iNJEcRr0qXjXZn5M9TLYTB1TnuGgkQch8Qkow/rPfxehuDggvUt73P6ZvU7DTOngsZunov4pD2reIkbgar63hdEI2OiP/HOwH+zw8LsfkrMTu9pjGYGsiRU=
