language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -U setuptools coverage coveralls numpy
  - pip install -r requirements.txt
script:
  coverage run manage.py test
after_success:
  coveralls
