language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y gfortran
install:
  - pip install -U setuptools coverage coveralls -r requirements.txt
script:
  coverage run manage.py test
after_success:
  coveralls
