language: python
python:
- '3.5'
- '3.6'
env:
- NODE_VERSION='7'
before_install:
- nvm install $NODE_VERSION
addons:
  apt:
    packages:
    - gfortran
install:
- pip install -U coverage coveralls
- pip install -r requirements.txt
- npm install
- npm run build
script: coverage run manage.py test
after_success: coveralls
