# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PI', 'Pricipal Investigator'), ('CI', 'Co-Investigator')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('abstract', models.TextField(blank=True, default='')),
                ('tac_priority', models.PositiveIntegerField()),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_allocation', models.FloatField(default=0)),
                ('std_time_used', models.FloatField(default=0)),
                ('ipp_limit', models.FloatField(default=0)),
                ('ipp_time_available', models.FloatField(default=0)),
                ('too_allocation', models.FloatField(default=0)),
                ('too_time_used', models.FloatField(default=0)),
                ('telescope_class', models.CharField(choices=[('2m0', '2m0'), ('1m0', '1m0'), ('0m8', '0m8'), ('0m4', '0m4')], max_length=20)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposal')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='TimeAllocationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='proposals',
            field=models.ManyToManyField(through='proposals.TimeAllocation', to='proposals.Proposal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.TimeAllocationGroup'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='users',
            field=models.ManyToManyField(through='proposals.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposal'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
