# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalinvite',
            name='created',
        ),
        migrations.AddField(
            model_name='proposalinvite',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
