# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalinvite',
            name='token',
        ),
        migrations.AddField(
            model_name='proposalinvite',
            name='email',
            field=models.EmailField(default='populate@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
