# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_semester_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ('title',)},
        ),
    ]
