# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20170418_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='public',
        ),
    ]
