# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_membership_time_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeallocation',
            options={'ordering': ('-semester__id',)},
        ),
    ]
