# Generated by Django 2.0.2 on 2018-02-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20171218_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeallocationgroup',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
