# Generated by Django 2.0.2 on 2018-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_timeallocationgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='non_science',
            field=models.BooleanField(default=False),
        ),
    ]
