# Generated by Django 2.0.3 on 2018-03-21 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_timeallocationgroup_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeallocationgroup',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
