# Generated by Django 2.0.4 on 2018-04-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_auto_20180321_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeallocationgroup',
            name='four_meter_alloc',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='0.4 Meter Alloc'),
        ),
    ]
