# Generated by Django 2.1.3 on 2018-11-29 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_auto_20181109_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Add notes here. Not visible to users.'),
        ),
        migrations.AlterField(
            model_name='timeallocation',
            name='too_allocation',
            field=models.FloatField(default=0, verbose_name='Rapid Response Allocation'),
        ),
        migrations.AlterField(
            model_name='timeallocation',
            name='too_time_used',
            field=models.FloatField(default=0, verbose_name='Rapid Response Time Used'),
        ),
    ]
