# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='simple_interface',
            field=models.BooleanField(default=False),
        ),
    ]
