# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_simple_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications_on_authored_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_authored_requests_only',
            field=models.BooleanField(default=False),
        ),
    ]
