# Generated by Django 2.1.3 on 2019-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170418_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
